services:
  - type: web
    name: mediassist-simple
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SITE_NAME
        value: MediAssist Simple
